spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_study?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: kimna04!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: "eY8#MnKlP2bQ7~fH5gRtY9o!sR1@Uv!3kZx$N2MpTjWtVh4Qz"

